// const countries = [
//   'Irlanda',
//   'Irlanda del Norte',
//   'Escocia',
//   'Wales',
//   'Inglaterra',
//   'Portugal',
//   'España',
//   'Francia',
//   'Belgica',
//   'Holanda',
//   'Suiza',
//   'Italia',
//   'Checoslovaquia',
//   'Alemania',
//   'Dinamarca',
//   'Noruega',
//   'Suecia',
//   'Finlandia',
//   'Polonia',
//   'Eslovaquia',
//   'Austria',
//   'Hungria',
//   'Croacia',
//   'Yugoslavia',
//   'Rumania',
//   'Bulgaria',
//   'Grecia',
//   'Turquia',
//   'Ucrania',
//   'Rusia',
//   'Marruecos',
//   'Tunez',
//   'Egipto',
//   'Nigeria',
//   'Camerun',
//   'Sudafrica',
//   'Estados Unidos',
//   'Mexico',
//   'Jamaica',
//   'Colombia',
//   'Brasil',
//   'Peru',
//   'Chile',
//   'Paraguay',
//   'Uruguay',
//   'Argentina',
//   'Japon',
//   'Corea del Sur',
//   'China',
//   'Iran',
//   'Emiratos Arabes',
//   'Arabia Saudita',
//   'Australia'
// ]

const countries = [
  'Argentina',
  'Australia',
  'Austria',
  'Belgium',
  'Brazil',
  'Bulgaria',
  'Cameroon',
  'Chile',
  'China',
  'Colombia',
  'Croatia',
  'Czech Republic',
  'Denmark',
  'Egypt',
  'England',
  'Finland',
  'France',
  'Germany',
  'Greece',
  'Hungary',
  'Iran',
  'Ireland',
  'Northern Ireland',
  'Italy',
  'Jamaica',
  'Japan',
  'Korea Republic',
  'Mexico',
  'Morocco',
  'Netherlands',
  'Nigeria',
  'Norway',
  'Paraguay',
  'Peru',
  'Poland',
  'Portugal',
  'Romania',
  'Russia',
  'Saudi Arabia',
  'Scotland',
  'Slovakia',
  'South Africa',
  'Spain',
  'Sweden',
  'Switzerland',
  'Tunisia',
  'Turkey',
  'USA',
  'United Arab Emirates',
  'Uruguay',
  'Yugoslavia',
  'Wales'
]

export default countries
